/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.AdminController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.AdminModel;

/**
 *
 * @author Kawayyy
 */
public class FrmAdmin extends javax.swing.JFrame {
    private AdminController control;
    private boolean status;
    private String proses;
    private List<AdminModel> listAdmin;
    private String[] tabelHeader;
    private DefaultTableModel dtm;
    int row;
    

    /**
     * Creates new form FrmAdminn
     */
    public FrmAdmin() {
        initComponents();
        control = new AdminController(this);
        txtUser.setText(AdminController.getUsername());
        txtNama.setText(AdminController.getNama());
        txtPassword.setText(AdminController.getPassword());
        txtEmail.setText(AdminController.getEmail());
        txtAlamat.setText(AdminController.getAlamat());
        txtTelp.setText(AdminController.getTelp());
        
        proses = "";
        tabelHeader = new String[]{"Username", "Nama Admin", "Password", "Alamat", "Telp", "Email"};
        dtm = new DefaultTableModel(null, tabelHeader);
        tblAdmin.setModel(dtm);
        tblAdmin.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            
            public void valueChanged(ListSelectionEvent e){
                row = tblAdmin.getSelectedRow();
                if(row >= 0){
                    txtUser.setText(dtm.getValueAt(row, 0).toString());
                    txtNama.setText(dtm.getValueAt(row, 1).toString());
                    txtPassword.setText(dtm.getValueAt(row, 2).toString());             
                    txtAlamat.setText(dtm.getValueAt(row, 3).toString());
                    txtTelp.setText(dtm.getValueAt(row, 4).toString());
                    txtEmail.setText(dtm.getValueAt(row, 5).toString());
                }
            }
        });
        refreshTable();
    }
    
    public void aturText(boolean status){
        txtCari.setEnabled(status);
        txtUser.setEnabled(status);
        txtNama.setEnabled(status);
        txtPassword.setEnabled(status);
        txtEmail.setEnabled(status);
        txtAlamat.setEnabled(status);
        txtTelp.setEnabled(status);
    }
    
    public void aturButton(boolean status){
        btnCari.setEnabled(status);
        btnSegar.setEnabled(status);
        btnTambah.setEnabled(status);
        btnSimpan.setEnabled(!status);
        btnHapus.setEnabled(status);
        btnEdit.setEnabled(status);
    }
    
    private void refreshTable(){
        if(proses.equalsIgnoreCase("")){
            listAdmin = control.selectAdmin("", "");
        }else if(proses.equals("CARI")){
            listAdmin = control.selectAdmin(txtCari.getText(), txtCari.getText());
        }
        
        dtm = (DefaultTableModel) tblAdmin.getModel();
        dtm.setRowCount(0);
        for(AdminModel data : listAdmin){
            dtm.addRow(new Object[]{
                data.getUsername(),
                data.getNama(),
                data.getPassword(),
                data.getAlamat(),
                data.getTelp(),
                data.getEmail()});
        }
        
        if(tblAdmin.getRowCount() > 0){
            row = tblAdmin.getRowCount() - 1;
            tblAdmin.setRowSelectionInterval(row, row);
            aturButton(true);
            aturText(true);
            proses = "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormAdmin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtAlamat = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAdmin = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        btnSegar = new javax.swing.JButton();
        btnKeluar1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FormAdmin.setBackground(new java.awt.Color(51, 51, 51));
        FormAdmin.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel1.setText("USERNAME");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 61, 65, 15);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel2.setText("NAMA");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 97, 36, 15);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel3.setText("EMAIL");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 175, 36, 15);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel5.setText("NOMER TLP/HP");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(409, 99, 89, 15);

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel6.setText("ALAMAT");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(409, 61, 48, 15);

        txtNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel3.add(txtNama);
        txtNama.setBounds(95, 97, 205, 30);
        jPanel3.add(txtUser);
        txtUser.setBounds(95, 59, 228, 30);

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel4.setText("PASSWORD");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 137, 65, 15);
        jPanel3.add(txtEmail);
        txtEmail.setBounds(95, 173, 228, 30);
        jPanel3.add(txtPassword);
        txtPassword.setBounds(95, 135, 185, 30);
        jPanel3.add(txtAlamat);
        txtAlamat.setBounds(503, 59, 194, 30);
        jPanel3.add(txtTelp);
        txtTelp.setBounds(502, 97, 141, 30);

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/employee3.png"))); // NOI18N
        jLabel7.setText("Data Admin");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(1, 11, 140, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/background 3.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 0, 1050, 220);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(11, 0, 1045, 220);

        jPanel4.setBackground(new java.awt.Color(255, 211, 173));

        btnTambah.setBackground(new java.awt.Color(0, 0, 0));
        btnTambah.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (163).png"))); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setPreferredSize(new java.awt.Dimension(87, 40));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 0, 0));
        btnSimpan.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (3).jpg"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.setPreferredSize(new java.awt.Dimension(87, 40));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 0, 0));
        btnEdit.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (146).png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setPreferredSize(new java.awt.Dimension(87, 40));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(0, 0, 0));
        btnHapus.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (167).png"))); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.setPreferredSize(new java.awt.Dimension(87, 40));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(0, 0, 0));
        btnKeluar.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (47).png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setPreferredSize(new java.awt.Dimension(87, 40));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(186, 226, 666, 41);

        txtCari.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 12)); // NOI18N
        txtCari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCari.setText("INI KOLOM PENCARIAN / BUKAN KOLOM IKAN");
        txtCari.setPreferredSize(new java.awt.Dimension(87, 30));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });
        jPanel2.add(txtCari);
        txtCari.setBounds(123, 295, 933, 40);

        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAdmin);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(11, 341, 1045, 123);

        btnCari.setBackground(new java.awt.Color(0, 0, 0));
        btnCari.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (5).jpg"))); // NOI18N
        btnCari.setText("CARI");
        btnCari.setPreferredSize(new java.awt.Dimension(87, 40));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel2.add(btnCari);
        btnCari.setBounds(27, 295, 87, 40);

        btnSegar.setBackground(new java.awt.Color(0, 0, 0));
        btnSegar.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnSegar.setForeground(new java.awt.Color(255, 255, 255));
        btnSegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (165).png"))); // NOI18N
        btnSegar.setText("REFRESH");
        btnSegar.setPreferredSize(new java.awt.Dimension(87, 40));
        btnSegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSegar);
        btnSegar.setBounds(858, 226, 127, 41);

        btnKeluar1.setBackground(new java.awt.Color(0, 0, 0));
        btnKeluar1.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnKeluar1.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/prev.png"))); // NOI18N
        btnKeluar1.setText("KEMBALI");
        btnKeluar1.setPreferredSize(new java.awt.Dimension(87, 40));
        btnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnKeluar1);
        btnKeluar1.setBounds(27, 226, 110, 41);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/background 3.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 1080, 500);

        FormAdmin.add(jPanel2);
        jPanel2.setBounds(10, 11, 1067, 498);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/background 3.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        FormAdmin.add(jLabel8);
        jLabel8.setBounds(-6, 0, 1100, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
       aturButton(false);
       aturText(true);
       btnKeluar.setText("Cancel");
       txtUser.setText(null);
       txtNama.setText(null);
       txtPassword.setText(null);
       txtEmail.setText(null);
       txtAlamat.setText(null);
       txtTelp.setText(null);
       txtUser.requestFocus();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        control.inputAdmin(txtUser.getText(), txtNama.getText(), txtPassword.getText(),
                txtAlamat.getText(), txtTelp.getText(),
                txtEmail.getText());
        
        boolean hasil = control.insertAdmin();
        if(hasil == false){
            JOptionPane.showMessageDialog(null, "Penyimpanan Gagal");
        }
        aturText(true);
        aturButton(true);
        refreshTable();
        btnKeluar.setText("Keluar");
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        control.inputUser(txtNama.getText(), txtPassword.getText(),
                txtAlamat.getText(), txtTelp.getText(),
                txtEmail.getText());
        
        boolean hasil = control.updateAdmin();
        if(hasil == false)
        {
            JOptionPane.showConfirmDialog(null, "Update data gagal");
        }
        else
        {
            JOptionPane.showConfirmDialog(null,"Update data Berhasil" );
        }
        refreshTable();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        control.inputAdmin(txtUser.getText(), txtNama.getText(), txtPassword.getText(),
                txtAlamat.getText(), txtTelp.getText(),
                txtEmail.getText());
        
        status = control.deleteAdmin();
        if(status == false){
            JOptionPane.showMessageDialog(null, "Maaf data tidak dapat dihapus karena digunakan "
            + "sebagai data pekerjaan orang tua pendaftar");
        }
        refreshTable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyPressed

    private void tblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAdminMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        proses = "CARI";
        refreshTable();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegarActionPerformed
        // TODO add your handling code here:
        refreshTable();
        txtCari.setText("");
    }//GEN-LAST:event_btnSegarActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        if (btnKeluar.getText().equals("Keluar")){
            dispose();
        }else {
            proses = "";
            aturText(true);
            aturButton(true);
            refreshTable();
            btnKeluar.setText("Keluar");
              }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluar1ActionPerformed
        // TODO add your handling code here:
        FrmMain form = new FrmMain();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormAdmin;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKeluar1;
    private javax.swing.JButton btnSegar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAdmin;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
