/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.BukuController;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;
import model.BukuModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Kawayyy
 */
public class FrmBuku extends javax.swing.JFrame {

    private BukuController control;
    private boolean status;
    private String proses;
    private List<BukuModel> listBuku;
    private String[] tabelHeader;
    private DefaultTableModel dtm;
    private int row;
    public FrmPeminjaman frmBuku = null;

    /**
     * Creates new form FrmPekerjaan
     */
    public FrmBuku() {
        initComponents();
        control = new BukuController(this);

        proses = "";
        tabelHeader = new String[]{"Nomor Buku", "Judul", "Pengarang", "Penerbit", "Kategori", "Tahun", "Rak", "Jumlah"};
        dtm = new DefaultTableModel(null, tabelHeader);
        tblBuku.setModel(dtm);
        tblBuku.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                row = tblBuku.getSelectedRow();
                if (row >= 0) {
                    txtNo_Buku.setText(dtm.getValueAt(row, 0).toString());
                    txtJudul.setText(dtm.getValueAt(row, 1).toString());
                    txtPengarang.setText(dtm.getValueAt(row, 2).toString());
                    txtPenerbit.setText(dtm.getValueAt(row, 3).toString());
                    txtKategori.setText(dtm.getValueAt(row, 4).toString());
                    txtTahun.setText(dtm.getValueAt(row, 5).toString());
                    txtRak.setText(dtm.getValueAt(row, 6).toString());
                    txtStok.setText(dtm.getValueAt(row, 7).toString());
                }
            }
        });
        refreshTable();
    }

    private void refreshTable() {
        if (proses.equalsIgnoreCase("")) {
            listBuku = control.selectBuku();

            dtm = (DefaultTableModel) tblBuku.getModel();
            dtm.setRowCount(0);
            for (BukuModel data : listBuku) {
                dtm.addRow(new Object[]{
                    data.getNo_buku(),
                    data.getJudul(),
                    data.getPengarang(),
                    data.getPenerbit(),
                    data.getKategori(),
                    data.getTahun(),
                    data.getRak(),
                    data.getJumlah()});
            }

            if (tblBuku.getRowCount() > 0) {
                row = tblBuku.getRowCount() - 1;
                tblBuku.setRowSelectionInterval(row, row);
                aturButton(true);
                aturText(false);
                proses = "";
            }
        }
    }

    public void aturText(boolean status) {
        txtCari.setEnabled(!status);
        txtNo_Buku.setEnabled(!status);
        txtJudul.setEnabled(!status);
        txtPengarang.setEnabled(!status);
        txtPenerbit.setEnabled(!status);
        txtKategori.setEnabled(!status);
        txtStok.setEnabled(!status);
        txtRak.setEnabled(!status);
    }

    public void aturButton(boolean status) {
        btnTambah.setEnabled(status);
        btnUbah.setEnabled(status);
        btnSimpan.setEnabled(!status);
        btnHapus.setEnabled(status);
        btnPrint.setEnabled(status);
        btnCari.setEnabled(status);
    }

    /**
     * Creates new form FrmPekerjaan
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        txtPengarang = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtKategori = new javax.swing.JTextField();
        txtNo_Buku = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPenerbit = new javax.swing.JTextField();
        txtRak = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        btnKeluar1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel1.setText("NO BUKU");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 40, 53, 15);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel2.setText("JUDUL");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 70, 34, 15);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel3.setText("PENGARANG");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 110, 76, 15);

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel4.setText("STOK");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(810, 70, 31, 15);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel5.setText("TAHUN TERBIT");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(330, 110, 83, 15);

        txtJudul.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulActionPerformed(evt);
            }
        });
        jPanel3.add(txtJudul);
        txtJudul.setBounds(150, 70, 156, 30);

        txtPengarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPengarangActionPerformed(evt);
            }
        });
        jPanel3.add(txtPengarang);
        txtPengarang.setBounds(150, 110, 156, 30);

        txtStok.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });
        jPanel3.add(txtStok);
        txtStok.setBounds(850, 70, 166, 30);

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel7.setText("JENIS BUKU");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(330, 70, 63, 15);

        txtKategori.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKategoriActionPerformed(evt);
            }
        });
        jPanel3.add(txtKategori);
        txtKategori.setBounds(430, 70, 367, 30);
        jPanel3.add(txtNo_Buku);
        txtNo_Buku.setBounds(150, 29, 156, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("PENERBIT");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(330, 40, 55, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("RAK");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(810, 40, 22, 15);

        txtPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenerbitActionPerformed(evt);
            }
        });
        jPanel3.add(txtPenerbit);
        txtPenerbit.setBounds(430, 29, 367, 30);
        jPanel3.add(txtRak);
        txtRak.setBounds(850, 29, 166, 30);

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (158).png"))); // NOI18N
        jLabel9.setText("Data Buku");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 0, 130, 32);
        jPanel3.add(txtTahun);
        txtTahun.setBounds(430, 110, 369, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/background 3.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(-10, -30, 1040, 180);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(11, 1, 1027, 140);

        jPanel4.setBackground(new java.awt.Color(255, 211, 173));

        btnTambah.setBackground(new java.awt.Color(0, 0, 0));
        btnTambah.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (163).png"))); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setPreferredSize(new java.awt.Dimension(87, 40));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 0, 0));
        btnSimpan.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (3).jpg"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.setPreferredSize(new java.awt.Dimension(87, 40));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(0, 0, 0));
        btnUbah.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (146).png"))); // NOI18N
        btnUbah.setText("EDIT");
        btnUbah.setPreferredSize(new java.awt.Dimension(87, 40));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(0, 0, 0));
        btnHapus.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (167).png"))); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.setPreferredSize(new java.awt.Dimension(87, 40));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(0, 0, 0));
        btnKeluar.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (47).png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setPreferredSize(new java.awt.Dimension(87, 40));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(190, 150, 706, 40);

        txtCari.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 12)); // NOI18N
        txtCari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCari.setText("INI KOLOM PENCARIAN / BUKAN KOLOM IKAN");
        txtCari.setPreferredSize(new java.awt.Dimension(87, 30));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });
        jPanel2.add(txtCari);
        txtCari.setBounds(120, 200, 918, 34);

        btnCari.setBackground(new java.awt.Color(0, 0, 0));
        btnCari.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (5).jpg"))); // NOI18N
        btnCari.setText("CARI");
        btnCari.setPreferredSize(new java.awt.Dimension(87, 40));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel2.add(btnCari);
        btnCari.setBounds(10, 200, 103, 34);

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        tblBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblBukuKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblBuku);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 250, 1027, 141);

        btnPrint.setBackground(new java.awt.Color(0, 0, 0));
        btnPrint.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (42).png"))); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.setPreferredSize(new java.awt.Dimension(87, 40));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);
        btnPrint.setBounds(910, 150, 127, 40);

        btnKeluar1.setBackground(new java.awt.Color(0, 0, 0));
        btnKeluar1.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnKeluar1.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/prev.png"))); // NOI18N
        btnKeluar1.setText("KEMBALI");
        btnKeluar1.setPreferredSize(new java.awt.Dimension(87, 40));
        btnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnKeluar1);
        btnKeluar1.setBounds(10, 150, 120, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/background 3.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, -6, 1050, 440);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1048;
        gridBagConstraints.ipady = 399;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 10, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/background 3.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -474;
        gridBagConstraints.ipady = -140;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jLabel10, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void txtPengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPengarangActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void txtKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKategoriActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        aturButton(false);
        aturText(false);
        btnKeluar.setText("Cancel");
        txtNo_Buku.setText(null);
        txtJudul.setText(null);
        txtPengarang.setText(null);
        txtPenerbit.setText(null);
        txtTahun.setText(null);
        txtKategori.setText(null);
        txtStok.setText(null);
        txtRak.setText(null);
        txtNo_Buku.requestFocus();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        control.inputBuku(txtNo_Buku.getText(), txtJudul.getText(), txtPengarang.getText(),
                txtPenerbit.getText(), txtKategori.getText(), txtTahun.getText(),
                txtStok.getText(), txtRak.getText());

        boolean hasil = control.insertBuku();
        if (hasil == false) {
            JOptionPane.showMessageDialog(null, "Penyimpanan Gagal");
        }
        aturText(true);
        aturButton(true);
        refreshTable();
        btnKeluar.setText("Keluar");
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        control.inputBuku(txtNo_Buku.getText(), txtJudul.getText(), txtPengarang.getText(),
                txtPenerbit.getText(), txtKategori.getText(), txtTahun.getText(),
                txtRak.getText(), txtStok.getText());

        boolean hasil = control.updateBuku();
        if (hasil == false) {
            JOptionPane.showConfirmDialog(null, "Update data gagal");
        } else {
            JOptionPane.showConfirmDialog(null, "Update data Berhasil");
        }
        refreshTable();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        control.inputBuku(txtNo_Buku.getText(), txtJudul.getText(), txtPengarang.getText(),
                txtPenerbit.getText(), txtKategori.getText(), txtTahun.getText(),
                txtRak.getText(), txtStok.getText());

        status = control.deleteBuku();
        if (status == false) {
            JOptionPane.showMessageDialog(null, "Maaf data tidak dapat dihapus karena digunakan "
                    + "sebagai data pekerjaan orang tua pendaftar");
        }
        refreshTable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyPressed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        // TODO add your handling code here:
        row = tblBuku.getSelectedRow();
        frmBuku.noBuku = tblBuku.getValueAt(row, 0).toString();
        frmBuku.judulBuku = tblBuku.getValueAt(row, 1).toString();
        frmBuku.bukuTerpilih();
        this.dispose();
    }//GEN-LAST:event_tblBukuMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        proses = "CARI";
        refreshTable();
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenerbitActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        if (btnKeluar.getText().equals("Keluar")) {
            dispose();
        } else {
            proses = "";
            aturText(true);
            aturButton(true);
            refreshTable();
            btnKeluar.setText("Keluar");
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            KoneksiDB koneksi = new KoneksiDB();
            koneksi.getkoneksi();
            try {
                Map<String, Object> parameter = new HashMap<String, Object>();

                File rpt = new File("src/report/LaporanBuku.jrxml");
                JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
                JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
                JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
                        parameter, koneksi.getkoneksi());
                JasperViewer.viewReport(jasPrint, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Laporan tidak ditemukan" + e);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void tblBukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblBukuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            proses = "CARI";
            refreshTable();
        }
    }//GEN-LAST:event_tblBukuKeyPressed

    private void btnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluar1ActionPerformed
        // TODO add your handling code here:
        FrmMain form = new FrmMain();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKeluar1;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtKategori;
    private javax.swing.JTextField txtNo_Buku;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPengarang;
    private javax.swing.JTextField txtRak;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
