/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import control.SiswaController;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import koneksi.KoneksiDB;
import model.SiswaModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Kawayyy
 */
public class FrmSiswa extends javax.swing.JFrame {
 private SiswaController control;
    private boolean status;
    private String proses;
    private List<SiswaModel> listSiswa;
    private String[] tabelHeader;
    private DefaultTableModel dtm;
    private int row;
    public FrmPeminjaman frmPinjam = null;

    /**
     * Creates new form DataKaryawan
     */
    public FrmSiswa() {
        initComponents();
        control = new SiswaController(this);
        
        tabelHeader = new String[]{"NISN", "Nama Siswa", "Kelas", "No Telepon", "Jenis Kelamin", "Alamat", "Agama"};
        dtm = new DefaultTableModel(null, tabelHeader);
        tblSiswa.setModel(dtm);
        tblSiswa.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            
            public void valueChanged(ListSelectionEvent e){
                row = tblSiswa.getSelectedRow();
                if(row >= 0){
                    txtNisn.setText(dtm.getValueAt(row, 0).toString());
                    txtNama.setText(dtm.getValueAt(row, 1).toString());
                    txtKelas.setText(dtm.getValueAt(row, 2).toString());
                    txtTelpon.setText(dtm.getValueAt(row, 3).toString());
                    rdCowo.isSelected();
                    txtAlamat.setText(dtm.getValueAt(row, 5).toString());
                    txtAgama.setText(dtm.getValueAt(row, 6).toString());
                    
                }
            }
        });
        refreshTable();
    }
    private void refreshTable(){
        listSiswa = control.selectSiswa("", "");
        
        dtm = (DefaultTableModel) tblSiswa.getModel();
        dtm.setRowCount(0);
        for (SiswaModel data : listSiswa){
            dtm.addRow(new Object[]{
            data.getNisnSiswa(),
            data.getNamaSiswa(),
            data.getKelasSiswa(),
            data.getNotelpSiswa(),
            data.getJeniskSiswa(),
            data.getAlamatSiswa(),
            data.getAgamaSiswa()});
        }

     
        if(tblSiswa.getRowCount() > 0){
            row = tblSiswa.getRowCount() - 1;
            tblSiswa.setRowSelectionInterval(row, row);
            aturButton(true);
            aturText(false);
            proses = "";
        
      }
   }
    
    public void aturText(boolean status){
        txtNisn.setEnabled(!status);
        txtNama.setEnabled(!status);
        txtKelas.setEnabled(!status);
        txtTelpon.setEnabled(!status);
        rdCowo.setEnabled(!status);
        rdCewe.setEnabled(!status);
        txtAgama.setEnabled(!status);
        txtAlamat.setEnabled(!status);
    }
    
    public void aturButton(boolean status){
        btnTambah.setEnabled(status);
        btnEdit.setEnabled(status);
        btnSimpan.setEnabled(!status);
        btnHapus.setEnabled(status);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtAgama = new javax.swing.JTextField();
        txtNisn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtTelpon = new javax.swing.JTextField();
        rdCowo = new javax.swing.JRadioButton();
        rdCewe = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txpencarian = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSiswa = new javax.swing.JTable();
        btcari = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(253, 218, 183));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel1.setText("NISN");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 57, 27, 15);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel2.setText("NAMA");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 97, 36, 15);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel3.setText("KELAS");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 135, 36, 15);

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel4.setText("JENIS KELAMIN");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(371, 57, 85, 15);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel5.setText("AGAMA");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(371, 97, 45, 15);

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel6.setText("ALAMAT");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(371, 135, 48, 15);

        txtNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel3.add(txtNama);
        txtNama.setBounds(96, 95, 166, 30);

        txtKelas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelasActionPerformed(evt);
            }
        });
        jPanel3.add(txtKelas);
        txtKelas.setBounds(96, 133, 166, 30);

        txtAgama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgamaActionPerformed(evt);
            }
        });
        jPanel3.add(txtAgama);
        txtAgama.setBounds(478, 95, 171, 30);
        jPanel3.add(txtNisn);
        txtNisn.setBounds(96, 55, 166, 30);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(478, 133, 282, 51);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("NO TELP");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 174, 50, 14);
        jPanel3.add(txtTelpon);
        txtTelpon.setBounds(96, 171, 166, 30);

        buttonGroup1.add(rdCowo);
        rdCowo.setForeground(new java.awt.Color(51, 51, 51));
        rdCowo.setText("Laki - Laki");
        jPanel3.add(rdCowo);
        rdCowo.setBounds(478, 54, 93, 23);

        buttonGroup1.add(rdCewe);
        rdCewe.setForeground(new java.awt.Color(51, 51, 51));
        rdCewe.setText("Perempuan");
        jPanel3.add(rdCewe);
        rdCewe.setBounds(589, 54, 110, 23);

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/student_icon3.png"))); // NOI18N
        jLabel8.setText("Data Siswa");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 11, 127, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/background 3.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(-6, 0, 990, 230);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(11, 1, 980, 230);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(993, 336, 0, 26);

        txpencarian.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 12)); // NOI18N
        txpencarian.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txpencarian.setText("INI KOLOM PENCARIAN / BUKAN KOLOM IKAN");
        txpencarian.setPreferredSize(new java.awt.Dimension(87, 30));
        txpencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpencarianActionPerformed(evt);
            }
        });
        txpencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txpencarianKeyPressed(evt);
            }
        });
        jPanel2.add(txpencarian);
        txpencarian.setBounds(104, 285, 883, 40);

        tblSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSiswaMouseClicked(evt);
            }
        });
        tblSiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblSiswaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblSiswa);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(11, 343, 976, 166);

        btcari.setBackground(new java.awt.Color(0, 0, 0));
        btcari.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btcari.setForeground(new java.awt.Color(255, 255, 255));
        btcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (5).jpg"))); // NOI18N
        btcari.setText("CARI");
        btcari.setPreferredSize(new java.awt.Dimension(87, 40));
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        jPanel2.add(btcari);
        btcari.setBounds(11, 284, 87, 40);

        btnTambah.setBackground(new java.awt.Color(0, 0, 0));
        btnTambah.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (163).png"))); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setPreferredSize(new java.awt.Dimension(87, 40));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel2.add(btnTambah);
        btnTambah.setBounds(341, 237, 120, 41);

        btnSimpan.setBackground(new java.awt.Color(0, 0, 0));
        btnSimpan.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (3).jpg"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.setPreferredSize(new java.awt.Dimension(87, 40));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);
        btnSimpan.setBounds(479, 237, 103, 40);

        btnEdit.setBackground(new java.awt.Color(0, 0, 0));
        btnEdit.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (146).png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setPreferredSize(new java.awt.Dimension(87, 40));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit);
        btnEdit.setBounds(600, 237, 103, 40);

        btnHapus.setBackground(new java.awt.Color(0, 0, 0));
        btnHapus.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (167).png"))); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.setPreferredSize(new java.awt.Dimension(87, 40));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus);
        btnHapus.setBounds(721, 237, 119, 41);

        btnKeluar.setBackground(new java.awt.Color(0, 0, 0));
        btnKeluar.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (47).png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setPreferredSize(new java.awt.Dimension(87, 40));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnKeluar);
        btnKeluar.setBounds(209, 237, 114, 40);

        btnPrint.setBackground(new java.awt.Color(0, 0, 0));
        btnPrint.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/icon (42).png"))); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.setPreferredSize(new java.awt.Dimension(87, 40));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);
        btnPrint.setBounds(858, 237, 129, 41);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/prev.png"))); // NOI18N
        btnBack.setText("KEMBALI");
        btnBack.setPreferredSize(new java.awt.Dimension(87, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack);
        btnBack.setBounds(11, 237, 114, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 3/background 3.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 0, 1020, 550);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasActionPerformed

    private void txtAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgamaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
       aturButton(false);
       aturText(false);
       btnKeluar.setText("Cancel");
       txtNisn.setText(null);
       txtNama.setText(null);
       txtKelas.setText(null);
       txtTelpon.setText(null);
       txtAgama.setText(null);
       txtAlamat.setText(null);
       txtNisn.requestFocus();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String jenisKelamin = " ";
        if(rdCowo.isSelected()==true){
            jenisKelamin = "Laki-Laki";
        }else{
            jenisKelamin = "Perempuan";
        }
        control.inputSiswa(txtNisn.getText(), txtNama.getText(), txtKelas.getText(),
                txtTelpon.getText(), jenisKelamin,
                txtAlamat.getText(), txtAgama.getText());
        
        status = control.insertSiswa();
        if(status == false){
            JOptionPane.showMessageDialog(null, "Penyimpanan Gagal");
        }
        aturText(true);
        aturButton(true);
        refreshTable();
        btnKeluar.setText("Keluar");
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String jenisKelamin = " ";
        if(rdCowo.isSelected()==true){
            jenisKelamin = "Laki-Laki";
        }else{
            jenisKelamin = "Perempuan";
        }
        control.inputSiswa(txtNisn.getText(), txtNama.getText(), txtKelas.getText(),
                txtTelpon.getText(), jenisKelamin,
                txtAlamat.getText(), txtAgama.getText());
        
        boolean hasil = control.updateSiswa();
        if(hasil == false)
        {
            JOptionPane.showConfirmDialog(null, "Update data gagal");
        }
        else
        {
            JOptionPane.showConfirmDialog(null,"Update data Berhasil" );
        }
        refreshTable();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String jenisKelamin = " ";
        if(rdCowo.isSelected()==true){
            jenisKelamin = "Laki-Laki";
        }else{
            jenisKelamin = "Perempuan";
        }
        control.inputSiswa(txtNisn.getText(), txtNama.getText(), txtKelas.getText(),
                txtTelpon.getText(), jenisKelamin,
                txtAlamat.getText(), txtAgama.getText());
        
        status = control.deleteSiswa();
        if(status == false){
            JOptionPane.showMessageDialog(null, "Maaf data tidak dapat dihapus karena digunakan "
            + "sebagai data pekerjaan orang tua pendaftar");
        }
        refreshTable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txpencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpencarianActionPerformed

    private void txpencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txpencarianKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpencarianKeyPressed

    private void tblSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSiswaMouseClicked
        // TODO add your handling code here:
        row = tblSiswa.getSelectedRow();
        frmPinjam.nisn = tblSiswa.getValueAt(row, 0).toString();
        frmPinjam.namaSiswa = tblSiswa.getValueAt(row, 1).toString();
        frmPinjam.siswaTerpilih();
        this.dispose();
    }//GEN-LAST:event_tblSiswaMouseClicked

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcariActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        if (btnKeluar.getText().equals("Keluar")){
            dispose();
        }else {
            proses = "";
            aturText(true);
            aturButton(true);
            refreshTable();
            btnKeluar.setText("Keluar");
              }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try{
            KoneksiDB koneksi = new KoneksiDB();
           koneksi.getkoneksi();
           try{
               Map<String, Object> parameter = new HashMap<String, Object>();
               
               File rpt = new File("src/report/LaporanSiswa.jrxml");
               JasperDesign jasDesign = JRXmlLoader.load(rpt);
               parameter.clear();
               JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
               JasperPrint jasPrint = JasperFillManager.fillReport(jasReport, 
                       parameter, koneksi.getkoneksi());
               JasperViewer.viewReport(jasPrint, false);
           } catch (Exception e){
               JOptionPane.showMessageDialog(null, "Laporan tidak ditemukan" + e);
           }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void tblSiswaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSiswaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            proses = "CARI";
            refreshTable();
        }
    }//GEN-LAST:event_tblSiswaKeyPressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FrmMain form = new FrmMain();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcari;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton rdCewe;
    private javax.swing.JRadioButton rdCowo;
    private javax.swing.JTable tblSiswa;
    private javax.swing.JTextField txpencarian;
    private javax.swing.JTextField txtAgama;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNisn;
    private javax.swing.JTextField txtTelpon;
    // End of variables declaration//GEN-END:variables
}
